name: recrafto
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.3+1
  flutter_svg: ^1.1.0
  cupertino_icons: ^1.0.2
  json_annotation: ^4.5.0
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  spider: ^3.2.0

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  surf_lint_rules: ^1.5.0
  
dependency_overrides:
  args: ^2.3.1
  meta: ^1.8.0
  path: ^1.8.2
  yaml: ^3.1.1

flutter:
  uses-material-design: true